obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.2, 0.2], [0.2, -0.2], [-0.2, -0.2], [-0.2, 0.2]]
footprint_inflation: 0.01
# robot_radius: 0.2
# distance to obstacle
inflation_radius: 0.4

# min_obstacle_dist: 0.5

max_obstacle_height: 0.6
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /base_scan, marking: true, clearing: true, expected_update_rate: 0}
